--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 04. 08. 18:34:04
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE edesseg;

--
-- Drop table `order_heads`
--
DROP TABLE IF EXISTS order_heads;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `orders`
--
DROP TABLE IF EXISTS orders;

--
-- Drop table `sweets`
--
DROP TABLE IF EXISTS sweets;

--
-- Drop table `categories`
--
DROP TABLE IF EXISTS categories;

--
-- Drop table `manufacturers`
--
DROP TABLE IF EXISTS manufacturers;

--
-- Set default database
--
USE edesseg;

--
-- Create table `manufacturers`
--
CREATE TABLE manufacturers (
  gyartoid INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  PRIMARY KEY (gyartoid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `categories`
--
CREATE TABLE categories (
  kategoriaid INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  PRIMARY KEY (kategoriaid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `sweets`
--
CREATE TABLE sweets (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  gyarto INT(11) NOT NULL,
  kategoria INT(11) NOT NULL,
  kep VARCHAR(255) DEFAULT NULL,
  reszletek VARCHAR(255) DEFAULT NULL,
  ar INT(11) NOT NULL,
  darab INT(11) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE sweets 
  ADD CONSTRAINT FK_gyartok FOREIGN KEY (gyarto)
    REFERENCES manufacturers(gyartoid) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE sweets 
  ADD CONSTRAINT FK_kategoria FOREIGN KEY (kategoria)
    REFERENCES categories(kategoriaid) ON DELETE NO ACTION;

--
-- Create table `orders`
--
CREATE TABLE orders (
  id INT(11) NOT NULL,
  edessegid INT(11) DEFAULT NULL,
  mennyiseg INT(11) DEFAULT NULL,
  rendeles_fej_id INT(11) NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE orders 
  ADD CONSTRAINT FK_rendeles_edessegid FOREIGN KEY (edessegid)
    REFERENCES sweets(ID) ON DELETE NO ACTION;

--
-- Create table `users`
--
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  email VARCHAR(50) NOT NULL,
  cim VARCHAR(255) NOT NULL,
  telefon VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `order_heads`
--
CREATE TABLE order_heads (
  id INT(11) NOT NULL AUTO_INCREMENT,
  datum DATE DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE order_heads 
  ADD CONSTRAINT FK_rendeles_fej_user_id FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE NO ACTION;

-- 
-- Dumping data for table manufacturers
--
INSERT INTO manufacturers VALUES
(1, 'HARIBO'),
(2, 'MILKA');

-- 
-- Dumping data for table categories
--
INSERT INTO categories VALUES
(1, 'gumicuki'),
(2, 'csoki');

-- 
-- Dumping data for table users
--
-- Table edesseg.users does not contain any data (it is empty)

-- 
-- Dumping data for table sweets
--
INSERT INTO sweets VALUES
(1, 'Haribo goldbaren gumicukor', 1, 1, NULL, 'Haribo goldbaren gumicukor - 100 g', 339, 150),
(2, 'Mogyorós Milka csoki', 2, 2, 'https://static.groby.hu/media/03a/3bc/conv/milka-egészmogyorós-100g-full.png', 'A Milka csokoládé finom, lágyan kényeztető csokoládéélmény. 100% alpesi tejből készült tejcsokoládé mogyoródarabkákkal. Üzletünkben több féle ízben kapható a Milka csoki.', 250, 200);

-- 
-- Dumping data for table order_heads
--
-- Table edesseg.order_heads does not contain any data (it is empty)

-- 
-- Dumping data for table orders
--
-- Table edesseg.orders does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;